language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  - "iojs"

# configure notifications (email, IRC, campfire etc)
# # please update this section to your needs!
# notifications:
  irc: "irc.freenode.org#2a2b"
